class CustomException(Exception):
    pass


class UserNotFoundError(CustomException):
    pass
